### ISSUE TITLE
Found a Printer, but Connecting Failed

### ISSUE THREAD

**Issue by GregS1000RR** [bitbank2/Thermal_Printer#1]
Hi, 

I tried to use your library with a similar printer (PeriPage) from same GOOJPRT brand on ESP32.

After changing the searched device name string, I was able to make ESP32 find the Printer, but when trying to connect it failed 

Any ideas ?
Greg

Win10-1909
Arduino : 1.8.12
ESP32 Core : 1.0.4

Result : 

`Preparing image buffer...
Scanning for BLE printer
Scan Result: Name: PeriPage_2FDB_BLE, Address: c0:15:83:1b:2f:db, manufacturer data: 0000c015831b2fdb, serviceUUID: 0000fee7-0000-1000-8000-00805f9b34fb 
A match!
c0:15:83:1b:2f:db
PeriPage_2FDB_BLE
Found Device :-)
Found a printer!, connecting...
 - Created client, connecting to c0:15:83:1b:2f:db
Connect failed`

**Comment by bitbank2** [comment]
I've seen strange connection failures lately with my Nano33 BLE, but not the ESP32. I'm not sure why it's happening. Have you tried it from different ESP32 devices? My only idea would be to install an older version of the ESP32 support and see if they recently broke something in the bluetooth stack.
