### ISSUE TITLE
Paperfeed for cat printer broken

### ISSUE THREAD

**Issue by TheNitek** [bitbank2/Thermal_Printer#13]
Paperfeed on the cat printer is currently broken. Looks like paperFeed and setPaper commands are currently mixed up.

paperFeed should be command id -95 and have a payload length of two. (according to this: https://github.com/amber-sixel/catprinter/blob/contrib/COMMANDS.md )

**Comment by bitbank2** [comment]
I found and fixed this and will update shortly. I'm adding 1D & 2D barcode along with this fix.
