### ISSUE TITLE
tpPrint on cat printer

### ISSUE THREAD

**Issue by TheNitek** [bitbank2/Thermal_Printer#14]
Unfortunately tpPrint doesn't do anything for me on my cat printer. After some reading I am wondering if text printing is even support by the cat. Is tpPrint supposed to work on it?

**Comment by bitbank2** [comment]
I documented this somewhere - the cat printer doesn't support text or barcode output; it can only do graphics. You can use the tpDrawCustomText() function to print Adafruit_GFX fonts one line at a time (as graphics).
