### ISSUE TITLE
peripage a2 very light text and images

### ISSUE THREAD

**Issue by Joshinken** [bitbank2/Thermal_Printer#44]
im using the peripage a2 printer, and it connects just fine (thought the mcu crashes when trying to load the printer width), all custom font text and all images are really light? text prints just fine as complete black, though the different fonts and bold and such dont work, but the moment you print an image, its barely visible
![7D883592-B9D2-4708-9353-5CB1C1225E71](https://user-images.githubusercontent.com/65787590/221328947-4961ebf7-6f38-41ca-8409-7ee5196d3cbc.jpg)

**Comment by Joshinken** [comment]
honestly for what im doing i just need the "huge font" to work, thats all i need. i can look past every single other issue that comes from this specific printer as long as i can just get a darker image here

**Comment by bitbank2** [comment]
Sorry, I'm not sure. Some printers have an "energy" setting which really sets how long the paper sits on the heating element. I don't know the full command set for the PeriPage, so I don't know how to set it (if it exists).
