### ISSUE TITLE
Do these printers support cable connections?

### ISSUE THREAD

**Issue by berkut0** [bitbank2/Thermal_Printer#49]
I just wonder if it is possible to communicate via wires instead of Bluetooth? Does USB work as an interface or just for power?

**Comment by bitbank2** [comment]
Some of the printers do support serial over USB. I believe the MTP-02 supports that. You would need to test each one. The less expensive cat/rabbit ones don't appear to support serial over USB, but might have an internal serial connector that you could use if you open the case.
