### ISSUE TITLE
PT-210 Auto Power-Off

### ISSUE THREAD

**Issue by Dr-PV** [bitbank2/Thermal_Printer#7]
First of all, thank you for the library which work very well.

However, I encountered a problem with PT-210 printer which power off automatically within (approx.) 10 minutes. I tried to solve this problem by printing something to the PT-210 within every 5 minutes period but the printer still power off by itself anyway.

Is there a way to disable this automatic power off on the PT-210 ?

Thank you.

PV

**Comment by bitbank2** [comment]
Hi PV,
Thanks for sharing that you find the code useful. I imagine there is some command to "keep awake" or to disable the sleep, but I don't know what it is :(. I found a publicly available document to discover the graphics commands, but don't know anything beyond that. Please let me know if you find any info. It may also be that it has to be powered+charging to stay awake. Have you tried that?
