### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by petejohanson** [bitbank2/Thermal_Printer#8]
Before peeking at the code.... Is this under a particular license?

**Comment by bitbank2** [comment]
Hmm - thanks for pointing that out. I rushed this out the door without considering the license. You're free to use it as you wish; do you need me to add a particular verbage to it?

**Comment by witnessmenow** [comment]
Something like MIT is a nice do whatever license!

**Comment by petejohanson** [comment]
Agreed, having an explicit "do whatever you want" with either MIT or BSD license is ideal. Otherwise, it's unclear, and not easy to use by other projects with explicit license compatibility requirements.

**Comment by bitbank2** [comment]
I updated it to use the Apache 2.0 license
